name: Build and Push Dockerimage
run-name: Build and Push Dockerimage
on:
  workflow_dispatch:
  push:
    paths: 
      - docker

jobs:
  dockerbuild-job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      #- name: DoLo-Action
      #  uses: docker://ocfork/dolo-action:latest
      #  with:
      #    args: "${{ secrets.GITHUB_TOKEN }}"
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
                
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64
          push: true
          tags: |
            ocfork/hw:latest
