name: DoLo Build and Push Dockerimage
run-name: DoLo Build and Push Dockerimage
on:
  workflow_dispatch:
  push:
    paths: 
      - docker

jobs:
  dockerbuild-job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - run: |
          echo $HOME/.docker/config.json
                
      - run: |
          cat $HOME/.docker/config.json
                
      - name: DoLo-Action
        uses: docker://ocfork/dolo-action:latest
        with:
          args: "${{ secrets.DOCKER_TOKEN }}"
    
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_TOKEN }}

      - run: |
          echo ls -la dc
                
      - run: |
          cat $HOME/.docker/config.json
                
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64
          push: true
          tags: |
            ocfork/hw:latest
