name: tests

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:

  check_skip_tests_job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[skip tests]')"
    outputs:
      SKIPTESTS: ${{ steps.check_skiptests_msg.outputs.SKIPTESTS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 2
    - name: check last changed files
      id: check_skiptests_msg
      run: |
        echo "ref: ${{ github.event.pull_request.head.ref }}"
        echo "repository: ${{ github.event.pull_request.head.repo.full_name }}"
        
        echo "--- git log -2 ---"
        git log -2
        echo "--- ---------- ---"

        echo "SKIPPING TESTS"
        echo "SKIPTESTS=1" >> $GITHUB_OUTPUT


  run_tests_job:
    runs-on: ubuntu-latest
    needs: check_skip_tests_job    
    if: "!needs.check_skip_tests_job.outputs.SKIPTESTS"

    steps:
    - name: Run the Tests
      run: |
        echo "The tests were all successfully executed"
