name: tests

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:

  check_skip_tests_job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[skip tests]')"
    outputs:
      SKIPTESTS: ${{ steps.check_skiptests_msg.outputs.SKIPTESTS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 2    # this is needed for getting the diff for the last commit

    - name: check if last commit contains only prerelease suffix removals 
      id: check_prereleasesuffixremoval
      shell: bash
      run: |
        export CHANGED_FILES=$(git diff --name-only HEAD~1)
        echo CHANGED FILES:
        echo $CHANGED_FILES
        if [ "$CHANGED_FILES" == "values.yaml" ]
        then
          echo "only values.yaml was changed, checking changes"
          echo "---- RAW DIFF last commit ----"
          git diff -w -U0 --color=always HEAD~1
          echo "---- -------------------- ----"

          export OLD_LINES=$(cat gitdiff.txt | grep -i "^- " | wc -l)
          export NEW_LINES=$(cat gitdiff.txt | grep -i "^+ " | wc -l)
          export NEW_LINES_WITH_EMPTY_PRS=$(cat gitdiff.txt | grep -i "^+ .*prereleasesuffix:\s*$" | wc -l)

          echo "OLD LINES ($OLD_LINES)"
          cat gitdiff.txt | grep -i "^- "
          echo "---- -------------------- ----"
          echo "NEW LINES ($NEW_LINES)"
          cat gitdiff.txt | grep -i "^+ "
          echo "---- -------------------- ----"
          echo "NEW LINES WITH EMPTY PRERELEASESUFFIX ($NEW_LINES_WITH_EMPTY_PRS)"
          cat gitdiff.txt | grep -i "^+ .*prereleasesuffix:\s*$" 
          echo "---- -------------------- ----"
          if [ "$OLD_LINES" != "$NEW_LINES" ]
          then
            echo "Number of old lines and new lines differs"
          else
            if [ "$NEW_LINES" != "$NEW_LINES_WITH_EMPTY_PRS" ]
            then
              echo "not all new lines are empty prereleasesuffixes"
            else
              echo "detected only prerelease suffix removals in changed files"
              echo "SKIPPING TESTS"
              echo "SKIPTESTS=1" >> $GITHUB_OUTPUT
            fi
          fi
        fi 


  run_tests_job:
    runs-on: ubuntu-latest
    needs: check_skip_tests_job    
    if: "!needs.check_skip_tests_job.outputs.SKIPTESTS"

    steps:
    - name: Run the Tests
      run: |
        echo "The tests were all successfully executed"
