
name: trigger_test

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[skip tests]')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        
    - name: do tests
      run: |
        echo executing the tests
