
name: trigger_test

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    

jobs:

  check_commit_message_job:
    runs-on: ubuntu-latest
    outputs:
      SKIPTESTS: ${{ steps.check_msg.outputs.SKIPTESTS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        
    - name: Check Message
      id: check_msg
      run: |
        message=$(git log -1 --format=oneline --pretty=format:"%s")
        echo "GIT COMMIT MESSAGE: $message"
        if echo $message | grep "\[skip tests\]" >/dev/null
        then
          echo "SKIPPING TESTS"
          echo "SKIPTESTS=1" >> $GITHUB_OUTPUT
        else
          echo "SKIPTESTS=" >> $GITHUB_OUTPUT
        fi

  run_tests_job:
    runs-on: ubuntu-latest
    needs: check_commit_message_job    
    if: "!needs.check_commit_message_job.outputs.SKIPTESTS"


    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: do tests
      run: |
        echo executing the tests
      