
name: trigger_test

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[skip tests]')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}


    - name: get commit msg
      id: commit_msg
      run: |
        message=$(git log -1 --format=oneline --pretty=format:"%s")
        echo "GIT COMMIT MESSAGE: $message"
        if echo $message | grep "\[skip tests\]" >/dev/null
        then
          echo "SKIPPING TESTS"
          echo "SKIPTESTS=1" >> $GITHUB_OUTPUT
        else
          echo "SKIPTESTS=" >> $GITHUB_OUTPUT
        fi
        
    - name: echo output
      run: |
        echo ${{ steps.commit_msg.outputs.SKIPTESTS }}
        
    - name: do tests 1
      if: steps.commit_msg.outputs.SKIPTESTS != 1
      run: |
        echo executing the tests

    - name: do tests
      if: "!steps.commit_msg.outputs.SKIPTESTS"
      run: |
        echo executing the tests
      